/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.hudi.metaserver.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2022-07-21")
public enum TAction implements org.apache.thrift.TEnum {
  COMMIT(1),
  DELTACOMMIT(2),
  CLEAN(3),
  ROLLBACK(4),
  SAVEPOINT(5),
  REPLACECOMMIT(6),
  COMPACTION(7),
  RESTORE(8);

  private final int value;

  private TAction(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TAction findByValue(int value) { 
    switch (value) {
      case 1:
        return COMMIT;
      case 2:
        return DELTACOMMIT;
      case 3:
        return CLEAN;
      case 4:
        return ROLLBACK;
      case 5:
        return SAVEPOINT;
      case 6:
        return REPLACECOMMIT;
      case 7:
        return COMPACTION;
      case 8:
        return RESTORE;
      default:
        return null;
    }
  }
}
