/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hudi.sink.utils;

import org.apache.flink.core.memory.MemorySegment;
import org.apache.flink.table.data.RowData;
import org.apache.flink.table.runtime.generated.NormalizedKeyComputer;
import org.apache.flink.table.runtime.operators.sort.SortUtil;

/**
 * A constant normalized key for sorting rows by their encoded Hudi record key.
 *
 * <p>The encoded record key is not stored in the buffered {@link RowData}, so the full key is
 * generated by {@link RecordKeySortComparator} during comparison. Returning a non-determining
 * normalized key forces the sort buffer to use that comparator for every pair of rows.
 */
public class RecordKeySortKeyComputer implements NormalizedKeyComputer {

  @Override
  public void putKey(RowData record, MemorySegment target, int offset) {
    SortUtil.minNormalizedKey(target, offset, 1);
  }

  @Override
  public int compareKey(MemorySegment segment1, int offset1, MemorySegment segment2, int offset2) {
    return 0;
  }

  @Override
  public void swapKey(MemorySegment segment1, int offset1, MemorySegment segment2, int offset2) {
    // All normalized keys are identical.
  }

  @Override
  public int getNumKeyBytes() {
    return 1;
  }

  @Override
  public boolean isKeyFullyDetermines() {
    return false;
  }

  @Override
  public boolean invertKey() {
    return false;
  }
}
