name: hudi-ci
trigger:
  change:
    types: [create, push]
jobs:
  unittest-hudi-common:
    name: hudi-metaserver
    image: hub.byted.org/codebase/ci_java8:latest
    steps:
      - name: install_thrift_test
        commands:
        - apt update
        - apt install thrift-compiler-0.12
        - ln -s bin/thrift /user/local/bin/thrift
      - name: hudi-metaserver
        commands:
          - mvn install  -DskipTests -pl :hudi-metaserver -Pthrift -am
          - mvn   -Punit-tests  clean test  -pl :hudi-metaserver