/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.trino.plugin.hudi;

import com.google.common.collect.ImmutableMap;
import io.trino.plugin.hudi.testing.CustomMergerHudiTablesInitializer;
import io.trino.plugin.hudi.testing.KeyBasedTestRecordMerger;
import io.trino.testing.AbstractTestQueryFramework;
import io.trino.testing.QueryRunner;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies that the Hudi Trino connector resolves and applies a user-supplied custom record merger
 * (configured via {@code hudi.record-merger-impls}) for Merge-On-Read tables whose record merge mode is
 * {@code CUSTOM}.
 * <p>
 * The test table is generated by {@link CustomMergerHudiTablesInitializer}: two record keys are inserted and
 * then upserted so each file group has a base file plus a log file. {@link KeyBasedTestRecordMerger} keeps the
 * newer record for keys ending in an odd digit and the older record otherwise, which makes the merged result
 * distinguishable from both the read-optimized (base-only) view and the built-in newest-wins behavior:
 * <ul>
 *   <li>{@code k1} (ends in odd digit): keeps the update -> value 99, name k1_updated</li>
 *   <li>{@code k2} (ends in even digit): keeps the base -> value 100, name k2_base</li>
 * </ul>
 * So on the real-time table {@code sum(value)} is 199 (99 + 100), whereas the base-only view yields 110
 * (10 + 100) and the built-in newest-wins would yield 104 (99 + 5).
 */
public class TestHudiCustomMerger
        extends AbstractTestQueryFramework
{
    @Override
    protected QueryRunner createQueryRunner()
            throws Exception
    {
        return HudiQueryRunner.builder()
                .setDataLoader(new CustomMergerHudiTablesInitializer())
                .addConnectorProperties(ImmutableMap.of(
                        "hudi.record-merger-impls", KeyBasedTestRecordMerger.class.getName()))
                .build();
    }

    @Test
    public void testReadOptimizedTableReturnsBaseFileValues()
    {
        // The read-optimized table reads base files only, so it reflects the initial insert.
        assertQuery(
                "SELECT key, name, value FROM " + CustomMergerHudiTablesInitializer.TABLE_NAME + " ORDER BY key",
                "VALUES ('k1', 'k1_base', CAST(10 AS BIGINT)), ('k2', 'k2_base', CAST(100 AS BIGINT))");
        assertThat(computeScalar("SELECT sum(value) FROM " + CustomMergerHudiTablesInitializer.TABLE_NAME))
                .isEqualTo(110L);
    }

    @Test
    public void testRealtimeTableAppliesCustomMerger()
    {
        // The real-time table merges base + log files. With the key-based custom merger:
        //  - k1 (odd) keeps the update (value 99, name k1_updated) -> proves merging happened (base was 10)
        //  - k2 (even) keeps the base (value 100, name k2_base) -> proves it is the custom rule, not newest-wins
        assertQuery(
                "SELECT key, name, value FROM " + CustomMergerHudiTablesInitializer.RT_TABLE_NAME + " ORDER BY key",
                "VALUES ('k1', 'k1_updated', CAST(99 AS BIGINT)), ('k2', 'k2_base', CAST(100 AS BIGINT))");
    }

    @Test
    public void testRealtimeTableSumIsDistinctFromBaseAndNewestWins()
    {
        // 199 uniquely identifies the custom merger: base-only would be 110, built-in newest-wins would be 104.
        assertThat(computeScalar("SELECT sum(value) FROM " + CustomMergerHudiTablesInitializer.RT_TABLE_NAME))
                .isEqualTo(199L);
    }
}
