/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.hudi.metadata;

import org.apache.hudi.client.SparkRDDWriteClient;
import org.apache.hudi.client.WriteStatus;
import org.apache.hudi.common.config.HoodieMetadataConfig;
import org.apache.hudi.common.data.HoodieData;
import org.apache.hudi.common.fs.FSUtils;
import org.apache.hudi.common.model.FileSlice;
import org.apache.hudi.common.model.HoodieBaseFile;
import org.apache.hudi.common.model.HoodieCommitMetadata;
import org.apache.hudi.common.model.HoodieFileGroupId;
import org.apache.hudi.common.model.HoodieIndexDefinition;
import org.apache.hudi.common.model.HoodieLogFile;
import org.apache.hudi.common.model.HoodieRecord;
import org.apache.hudi.common.model.HoodieTableType;
import org.apache.hudi.common.model.HoodieWriteStat;
import org.apache.hudi.common.model.WriteOperationType;
import org.apache.hudi.common.table.HoodieTableConfig;
import org.apache.hudi.common.table.HoodieTableMetaClient;
import org.apache.hudi.common.table.HoodieTableVersion;
import org.apache.hudi.common.table.view.FileSystemViewManager;
import org.apache.hudi.common.table.view.FileSystemViewStorageConfig;
import org.apache.hudi.common.table.view.FileSystemViewStorageType;
import org.apache.hudi.common.table.view.HoodieTableFileSystemView;
import org.apache.hudi.common.table.view.TableFileSystemView;
import org.apache.hudi.common.util.Lazy;
import org.apache.hudi.common.util.Option;
import org.apache.hudi.common.util.collection.Pair;
import org.apache.hudi.config.HoodieCompactionConfig;
import org.apache.hudi.config.HoodieIndexConfig;
import org.apache.hudi.config.HoodieWriteConfig;
import org.apache.hudi.data.HoodieJavaRDD;
import org.apache.hudi.index.HoodieIndex;
import org.apache.hudi.metadata.index.bloomfilters.BloomFiltersIndexer;
import org.apache.hudi.metadata.index.columnstats.ColumnStatsIndexer;
import org.apache.hudi.metadata.index.model.IndexInitializationContext;
import org.apache.hudi.metadata.index.model.IndexInitializationPlan;
import org.apache.hudi.metadata.index.model.IndexPartitionAndRecords;
import org.apache.hudi.metadata.index.model.IndexUpdateContext;
import org.apache.hudi.metadata.index.partitionstats.PartitionStatsIndexer;
import org.apache.hudi.metadata.index.record.BaseRecordIndexer;
import org.apache.hudi.metadata.index.record.RecordIndexer;
import org.apache.hudi.metadata.model.FileSliceAndPartition;
import org.apache.hudi.storage.StoragePath;
import org.apache.hudi.table.HoodieTable;
import org.apache.hudi.testutils.HoodieClientTestBase;
import org.apache.hudi.testutils.TaskFileAccessRecordingFileSystem;
import org.apache.hudi.testutils.TaskFileAccessRecordingFileSystem.Access;

import org.apache.spark.Dependency;
import org.apache.spark.rdd.RDD;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Deque;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.Function;
import java.util.stream.Collectors;

import scala.collection.JavaConverters;

import static org.apache.hudi.common.testutils.HoodieTestDataGenerator.TRIP_EXAMPLE_SCHEMA;
import static org.apache.hudi.testutils.Assertions.assertNoWriteErrors;
import static org.apache.hudi.testutils.TaskPayloadTestUtils.serializedClasses;
import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests that the metadata table index records of a commit are generated by tasks that carry neither the table
 * state (write config, meta clients, table metadata, file system views) nor per-task metadata table I/O.
 */
class TestMetadataIndexTaskPayload extends HoodieClientTestBase {

  private static final List<Class<?>> TABLE_STATE_TYPES = Arrays.asList(HoodieTable.class, HoodieWriteConfig.class,
      HoodieTableMetaClient.class, HoodieTableMetadata.class, FileSystemViewManager.class, TableFileSystemView.class);
  private static final List<Class<?>> FILE_SLICE_TYPES = Arrays.asList(FileSlice.class, HoodieBaseFile.class, HoodieLogFile.class);
  private static final String METADATA_FOLDER = "/.hoodie/metadata";
  private static final int FIRST_COMMIT_RECORDS = 60;

  private HoodieWriteConfig writeConfig;
  private HoodieCommitMetadata commitMetadata;
  private String instantTime;

  @BeforeEach
  void registerRecordingFileSystem() {
    TaskFileAccessRecordingFileSystem.register(jsc.hadoopConfiguration());
  }

  @ParameterizedTest
  @EnumSource(HoodieTableType.class)
  void testSecondaryIndexUpdateLooksUpFileSlicesOnDriver(HoodieTableType tableType) throws Exception {
    writeInflightCommit(tableType);
    HoodieIndexDefinition indexDefinition = secondaryIndexDefinition();
    TaskFileAccessRecordingFileSystem.reset();
    HoodieData<HoodieRecord> records = SecondaryIndexRecordGenerationUtils.convertWriteStatsToSecondaryIndexRecords(
        commitMetadata.getWriteStats(), instantTime, indexDefinition, writeConfig.getMetadataConfig(), metaClient, context, writeConfig, commitMetadata);
    List<HoodieRecord> generated = records.collectAsList();
    List<String> metadataTableAccesses = taskAccesses(path -> path.contains(METADATA_FOLDER));
    assertAll(
        () -> assertFalse(generated.isEmpty(), "No index records were generated"),
        () -> assertTrue(metadataTableAccesses.isEmpty(), "Secondary index tasks accessed the metadata table: " + metadataTableAccesses),
        () -> assertLineageCarriesNone(records, TABLE_STATE_TYPES));
  }

  @ParameterizedTest
  @EnumSource(HoodieTableType.class)
  void testSecondaryIndexUpdateWithTimelineServer(HoodieTableType tableType) throws Exception {
    // with the timeline server, the previous file slices are looked up on the remote view; the records are the same
    writeInflightCommit(tableType);
    HoodieIndexDefinition indexDefinition = secondaryIndexDefinition();
    HoodieWriteConfig remoteViewConfig = HoodieWriteConfig.newBuilder().withProperties(writeConfig.getProps())
        .withFileSystemViewConfig(FileSystemViewStorageConfig.newBuilder()
            .withStorageType(FileSystemViewStorageType.REMOTE_FIRST)
            .withRemoteServerHost("localhost")
            .withRemoteServerPort(timelineServicePort)
            .withEnableBackupForRemoteFileSystemView(false)
            .build())
        .build();
    Set<String> expected = SecondaryIndexRecordGenerationUtils.convertWriteStatsToSecondaryIndexRecords(commitMetadata.getWriteStats(), instantTime,
            indexDefinition, writeConfig.getMetadataConfig(), metaClient, context, writeConfig, commitMetadata)
        .collectAsList().stream().map(TestMetadataIndexTaskPayload::describe).collect(Collectors.toSet());

    TaskFileAccessRecordingFileSystem.reset();
    HoodieData<HoodieRecord> records = SecondaryIndexRecordGenerationUtils.convertWriteStatsToSecondaryIndexRecords(commitMetadata.getWriteStats(),
        instantTime, indexDefinition, remoteViewConfig.getMetadataConfig(), metaClient, context, remoteViewConfig, commitMetadata);
    Set<String> generated = records.collectAsList().stream().map(TestMetadataIndexTaskPayload::describe).collect(Collectors.toSet());
    List<String> metadataTableAccesses = taskAccesses(path -> path.contains(METADATA_FOLDER));
    assertAll(
        () -> assertFalse(generated.isEmpty(), "No index records were generated"),
        () -> assertEquals(expected, generated),
        () -> assertTrue(metadataTableAccesses.isEmpty(), "Secondary index tasks accessed the metadata table: " + metadataTableAccesses),
        () -> assertLineageCarriesNone(records, TABLE_STATE_TYPES));
  }

  private static HoodieIndexDefinition secondaryIndexDefinition() {
    return HoodieIndexDefinition.newBuilder()
        .withIndexName("secondary_index_idx_rider")
        .withIndexType(MetadataPartitionType.SECONDARY_INDEX.name())
        .withVersion(HoodieIndexVersion.getCurrentVersion(HoodieTableVersion.current(), "secondary_index_idx_rider"))
        .withIndexFunction("")
        .withSourceFields(Collections.singletonList("rider"))
        .withIndexOptions(Collections.emptyMap())
        .build();
  }

  private static String describe(HoodieRecord record) {
    return record.getRecordKey() + "|" + record.getPartitionPath() + "|" + ((HoodieMetadataPayload) record.getData()).isDeleted();
  }

  @ParameterizedTest
  @EnumSource(HoodieTableType.class)
  void testPartitionStatsUpdateReadsEachFileOnce(HoodieTableType tableType) throws Exception {
    writeInflightCommit(tableType);
    try (HoodieBackedTableMetadata tableMetadata = newTableMetadata()) {
      assertPartitionStatsUpdate(tableMetadata);
    }
  }

  @ParameterizedTest
  @EnumSource(HoodieTableType.class)
  void testFilesToFetchColumnStatsDoNotDependOnPartitionBatches(HoodieTableType tableType) throws Exception {
    writeInflightCommit(tableType);
    Map<String, List<HoodieWriteStat>> writeStatsByPartition = commitMetadata.getWriteStats().stream()
        .collect(Collectors.groupingBy(HoodieWriteStat::getPartitionPath));
    assertTrue(writeStatsByPartition.size() > 1, "The commit should write several partitions");
    String maxInstantTime = HoodieMetadataWriteUtils.getMaxInstantTime(metaClient, instantTime);
    try (HoodieBackedTableMetadata tableMetadata = newTableMetadata()) {
      Map<String, Set<String>> inOneBatch = HoodieMetadataWriteUtils.getFilesToFetchColumnStats(writeStatsByPartition, metaClient, tableMetadata,
          writeConfig, maxInstantTime, instantTime, Collections.emptyMap(), Integer.MAX_VALUE);
      Map<String, Set<String>> inBatchesOfOne = HoodieMetadataWriteUtils.getFilesToFetchColumnStats(writeStatsByPartition, metaClient, tableMetadata,
          writeConfig, maxInstantTime, instantTime, Collections.emptyMap(), 1);
      assertEquals(writeStatsByPartition.keySet(), inOneBatch.keySet());
      assertTrue(inOneBatch.values().stream().anyMatch(files -> !files.isEmpty()), "No committed files need column stats");
      assertEquals(inOneBatch, inBatchesOfOne);
    }
  }

  @ParameterizedTest
  @EnumSource(HoodieTableType.class)
  void testColumnStatsUpdateTasksCarryNoTableState(HoodieTableType tableType) throws Exception {
    writeInflightCommit(tableType);
    try (HoodieBackedTableMetadata tableMetadata = newTableMetadata()) {
      assertIndexRecords(new ColumnStatsIndexer(context, writeConfig, metaClient).buildUpdate(updateContext(tableMetadata)).get(0).indexRecords(),
          TABLE_STATE_TYPES);
    }
  }

  @ParameterizedTest
  @EnumSource(HoodieTableType.class)
  void testBloomFilterUpdateTasksCarryNoTableState(HoodieTableType tableType) throws Exception {
    writeInflightCommit(tableType);
    try (HoodieBackedTableMetadata tableMetadata = newTableMetadata()) {
      assertIndexRecords(new BloomFiltersIndexer(context, writeConfig, metaClient).buildUpdate(updateContext(tableMetadata)).get(0).indexRecords(),
          TABLE_STATE_TYPES);
    }
  }

  @ParameterizedTest
  @EnumSource(HoodieTableType.class)
  void testRecordIndexUpdateTasksCarryNoTableState(HoodieTableType tableType) throws Exception {
    writeInflightCommit(tableType);
    assertIndexRecords(BaseRecordIndexer.convertMetadataToRecordIndexRecords(context, commitMetadata, writeConfig.getMetadataConfig(),
        metaClient, writeConfig.getWritesFileIdEncoding(), instantTime), TABLE_STATE_TYPES);
  }

  @ParameterizedTest
  @EnumSource(HoodieTableType.class)
  void testRecordTaggingShipsNoFileSlices(HoodieTableType tableType) throws Exception {
    writeInflightCommit(tableType);
    List<HoodieRecord> columnStatsRecords;
    try (HoodieBackedTableMetadata tableMetadata = newTableMetadata()) {
      columnStatsRecords = new ColumnStatsIndexer(context, writeConfig, metaClient).buildUpdate(updateContext(tableMetadata)).get(0)
          .indexRecords().collectAsList();
    }
    assertRecordTagging(columnStatsRecords);
  }

  @ParameterizedTest
  @EnumSource(HoodieTableType.class)
  void testRecordIndexBootstrapResolvesSchemaOnce(HoodieTableType tableType) throws Exception {
    writeInflightCommit(tableType);
    List<FileSliceAndPartition> latestFileSlices = getCommittedFileSlices();
    // without a write schema the bootstrap resolves the table schema from the timeline
    Properties propsWithoutSchema = new Properties();
    propsWithoutSchema.putAll(writeConfig.getProps());
    propsWithoutSchema.remove(HoodieWriteConfig.AVRO_SCHEMA_STRING.key());
    HoodieWriteConfig configWithoutSchema = HoodieWriteConfig.newBuilder().withProperties(propsWithoutSchema).build();

    TaskFileAccessRecordingFileSystem.reset();
    IndexInitializationPlan plan = new RecordIndexer(context, configWithoutSchema, metaClient).buildInitialization(IndexInitializationContext.of(
        instantTime, instantTime, Collections.emptyMap(), Lazy.eagerly(latestFileSlices), Lazy.eagerly(Option.empty()))).get(0);
    List<String> timelineAccesses = taskAccesses(path -> path.contains("/.hoodie/timeline"));

    HoodieData<HoodieRecord> records = plan.dataPartitionAndRecords().get(0).indexRecords();
    assertAll(
        () -> assertEquals(FIRST_COMMIT_RECORDS, records.collectAsList().size()),
        () -> assertTrue(timelineAccesses.isEmpty(), "Record index bootstrap tasks accessed the timeline: " + timelineAccesses),
        () -> assertLineageCarriesNone(records, TABLE_STATE_TYPES));
  }

  private void assertPartitionStatsUpdate(HoodieBackedTableMetadata tableMetadata) throws IOException {
    TaskFileAccessRecordingFileSystem.reset();
    HoodieData<HoodieRecord> records = PartitionStatsIndexer.convertMetadataToPartitionStatsRecords(commitMetadata, instantTime, context, writeConfig,
        metaClient, tableMetadata, writeConfig.getMetadataConfig(), Option.of(writeConfig.getRecordMerger().getRecordType()), false);
    List<HoodieRecord> generated = records.collectAsList();
    // the column stats lookup reads every column stats file slice with all key prefixes, which are broadcast
    String keyPrefix = new ColumnStatsIndexPrefixRawKey(((HoodieMetadataPayload) generated.get(0).getData()).getColumnStatMetadata().get().getColumnName(),
        commitMetadata.getWriteStats().get(0).getPartitionPath()).encode();
    String serializedLineage = serializedLineage(records);
    List<String> filesPartitionAccesses = taskAccesses(path -> path.contains(METADATA_FOLDER + "/" + MetadataPartitionType.FILES.getPartitionPath() + "/"));
    // each column stats file is read by one task, and each written base file has its footer read once
    Map<String, Set<Long>> columnStatsReaders = TaskFileAccessRecordingFileSystem.taskOpens().stream()
        .filter(access -> access.getPath().contains(METADATA_FOLDER + "/" + MetadataPartitionType.COLUMN_STATS.getPartitionPath() + "/"))
        .collect(Collectors.groupingBy(Access::getPath, Collectors.mapping(Access::getTaskAttemptId, Collectors.toSet())));
    Set<String> writtenBaseFiles = commitMetadata.getWriteStats().stream().map(HoodieWriteStat::getPath)
        .filter(path -> FSUtils.isBaseFile(new StoragePath(path))).collect(Collectors.toSet());
    List<Access> writtenBaseFileOpens = TaskFileAccessRecordingFileSystem.taskOpens().stream()
        .filter(access -> writtenBaseFiles.stream().anyMatch(access.getPath()::endsWith))
        .collect(Collectors.toList());
    assertAll(
        () -> assertFalse(generated.isEmpty(), "No index records were generated"),
        () -> assertTrue(filesPartitionAccesses.isEmpty(), "Partition stats tasks listed the data table: " + filesPartitionAccesses),
        () -> assertFalse(columnStatsReaders.isEmpty(), "No column stats of committed files were read"),
        () -> assertTrue(columnStatsReaders.values().stream().allMatch(tasks -> tasks.size() == 1), "Column stats files read by several tasks: " + columnStatsReaders),
        () -> assertEquals(writtenBaseFiles.size(), writtenBaseFileOpens.size(), "Written base files opened more than once: " + writtenBaseFileOpens),
        () -> assertFalse(serializedLineage.contains(keyPrefix), "Task payload carries the column stats key prefix " + keyPrefix),
        // the column stats of the committed files are read with one metadata table lookup, which carries the table metadata
        () -> assertLineageCarriesNone(records, Collections.singletonList(HoodieWriteConfig.class)));
  }

  private void assertRecordTagging(List<HoodieRecord> columnStatsRecords) throws Exception {
    try (SparkHoodieBackedTableMetadataWriter metadataWriter =
             (SparkHoodieBackedTableMetadataWriter) SparkHoodieBackedTableMetadataWriter.create(storageConf, writeConfig, context)) {
      String columnStatsPartition = MetadataPartitionType.COLUMN_STATS.getPartitionPath();
      Pair<HoodieData<HoodieRecord>, List<HoodieFileGroupId>> tagged = metadataWriter.tagRecordsWithLocation(
          Collections.singletonList(IndexPartitionAndRecords.of(columnStatsPartition, context.parallelize(columnStatsRecords, 2))), false);
      assertLineageCarriesNone(tagged.getKey(), FILE_SLICE_TYPES);
      Set<String> fileIds = tagged.getValue().stream().map(HoodieFileGroupId::getFileId).collect(Collectors.toSet());
      List<HoodieRecord> taggedRecords = tagged.getKey().collectAsList();
      assertEquals(columnStatsRecords.size(), taggedRecords.size());
      assertTrue(taggedRecords.stream().allMatch(record -> fileIds.contains(record.getCurrentLocation().getFileId())));
    }
  }

  private HoodieBackedTableMetadata newTableMetadata() {
    return new HoodieBackedTableMetadata(context, metaClient.getStorage(), writeConfig.getMetadataConfig(), basePath);
  }

  private IndexUpdateContext updateContext(HoodieBackedTableMetadata tableMetadata) {
    return IndexUpdateContext.of(instantTime, tableMetadata, Lazy.lazily(() -> null), commitMetadata);
  }

  private void assertIndexRecords(HoodieData<HoodieRecord> records, List<Class<?>> forbiddenTypes) {
    assertLineageCarriesNone(records, forbiddenTypes);
    assertFalse(records.collectAsList().isEmpty(), "No index records were generated");
  }

  private void writeInflightCommit(HoodieTableType tableType) throws Exception {
    Properties props = new Properties();
    props.put(HoodieTableConfig.ORDERING_FIELDS.key(), "timestamp");
    initMetaClient(tableType, props);
    writeConfig = HoodieWriteConfig.newBuilder().withPath(basePath)
        .withSchema(TRIP_EXAMPLE_SCHEMA)
        .forTable("test_metadata_index_task_payload")
        .withParallelism(4, 4)
        .withEmbeddedTimelineServerEnabled(false)
        .withFileSystemViewConfig(FileSystemViewStorageConfig.newBuilder().withStorageType(FileSystemViewStorageType.MEMORY).build())
        .withIndexConfig(HoodieIndexConfig.newBuilder().withIndexType(HoodieIndex.IndexType.BLOOM).build())
        .withCompactionConfig(HoodieCompactionConfig.newBuilder().compactionSmallFileSize(0).withInlineCompaction(false).build())
        .withMetadataConfig(HoodieMetadataConfig.newBuilder().enable(true)
            .withMetadataIndexColumnStats(true)
            .withMetadataIndexPartitionStats(true)
            .withMetadataIndexBloomFilter(true)
            .withEnableGlobalRecordLevelIndex(true)
            .build())
        .build();
    try (SparkRDDWriteClient client = new SparkRDDWriteClient(context, writeConfig)) {
      String firstInstant = client.startCommit();
      List<WriteStatus> firstStatuses = client.insert(jsc.parallelize(dataGen.generateInserts(firstInstant, FIRST_COMMIT_RECORDS), 4), firstInstant).collect();
      assertNoWriteErrors(firstStatuses);
      client.commit(firstInstant, jsc.parallelize(firstStatuses));

      // the second commit stays inflight, as it is when the metadata writer generates its index records
      instantTime = client.startCommit();
      List<HoodieRecord> records = new ArrayList<>(dataGen.generateInserts(instantTime, 30));
      records.addAll(dataGen.generateUniqueUpdates(instantTime, 2));
      List<WriteStatus> statuses = client.upsert(jsc.parallelize(records, 3), instantTime).collect();
      assertNoWriteErrors(statuses);
      commitMetadata = new HoodieCommitMetadata();
      commitMetadata.setOperationType(WriteOperationType.UPSERT);
      commitMetadata.addMetadata(HoodieCommitMetadata.SCHEMA_KEY, TRIP_EXAMPLE_SCHEMA);
      statuses.forEach(status -> commitMetadata.addWriteStat(status.getStat().getPartitionPath(), status.getStat()));
    }
    metaClient = HoodieTableMetaClient.reload(metaClient);
  }

  private List<FileSliceAndPartition> getCommittedFileSlices() {
    HoodieTableMetadata metadata = new HoodieBackedTableMetadata(context, metaClient.getStorage(), writeConfig.getMetadataConfig(), basePath);
    try (HoodieTableFileSystemView view = new HoodieTableFileSystemView(metadata, metaClient,
        metaClient.getActiveTimeline().getCommitsTimeline().filterCompletedInstants())) {
      String latestInstant = metaClient.getActiveTimeline().getCommitsTimeline().filterCompletedInstants().lastInstant().get().requestedTime();
      view.loadAllPartitions();
      return Arrays.stream(dataGen.getPartitionPaths())
          .flatMap(partition -> view.getLatestMergedFileSlicesBeforeOrOn(partition, latestInstant)
              .map(fileSlice -> FileSliceAndPartition.of(partition, fileSlice)))
          .collect(Collectors.toList());
    }
  }

  private static List<String> taskAccesses(Function<String, Boolean> pathFilter) {
    List<String> accesses = new ArrayList<>();
    TaskFileAccessRecordingFileSystem.taskOpens().stream().filter(access -> pathFilter.apply(access.getPath()))
        .forEach(access -> accesses.add("open " + access));
    TaskFileAccessRecordingFileSystem.taskListings().stream().filter(access -> pathFilter.apply(access.getPath()))
        .forEach(access -> accesses.add("list " + access));
    return accesses;
  }

  /**
   * Asserts that no RDD in the lineage of {@code data}, nor a shuffle dependency between them, serializes an object of
   * the given types. Each of them is part of the task binary of some stage.
   */
  private static void assertLineageCarriesNone(HoodieData<?> data, List<Class<?>> forbiddenTypes) {
    Set<Class<?>> classes = new HashSet<>();
    lineage(data).forEach(object -> classes.addAll(serializedClasses(object)));
    Set<String> found = classes.stream()
        .filter(clazz -> forbiddenTypes.stream().anyMatch(forbidden -> forbidden.isAssignableFrom(clazz)))
        .map(Class::getName)
        .collect(Collectors.toCollection(TreeSet::new));
    assertTrue(found.isEmpty(), "Task payload carries " + found);
  }

  /**
   * Returns every RDD in the lineage of {@code data} and every dependency between them, each of which is part of the
   * task binary of some stage.
   */
  private static List<Object> lineage(HoodieData<?> data) {
    List<Object> lineage = new ArrayList<>();
    Set<Integer> visited = new HashSet<>();
    Deque<RDD<?>> toVisit = new ArrayDeque<>();
    toVisit.add(HoodieJavaRDD.getJavaRDD(data).rdd());
    while (!toVisit.isEmpty()) {
      RDD<?> rdd = toVisit.poll();
      if (visited.add(rdd.id())) {
        lineage.add(rdd);
        for (Dependency<?> dependency : JavaConverters.seqAsJavaList(rdd.dependencies())) {
          lineage.add(dependency);
          toVisit.add(dependency.rdd());
        }
      }
    }
    return lineage;
  }

  private static String serializedLineage(HoodieData<?> data) throws IOException {
    ByteArrayOutputStream bytes = new ByteArrayOutputStream();
    try (ObjectOutputStream out = new ObjectOutputStream(bytes)) {
      for (Object object : lineage(data)) {
        out.writeObject(object);
      }
    }
    return new String(bytes.toByteArray(), StandardCharsets.ISO_8859_1);
  }
}
