/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hudi.io.cdc;

import org.apache.hudi.common.model.HoodieRecord;
import org.apache.hudi.common.util.Option;

import java.io.Closeable;
import java.util.Map;

/**
 * Writes CDC records generated by merge handles.
 */
public interface HoodieCDCLogWriter<T> extends Closeable {

  default void put(HoodieRecord hoodieRecord, T oldRecord, Option<T> newRecord) {
    put(hoodieRecord.getRecordKey(), oldRecord, newRecord);
  }

  void put(String recordKey, T oldRecord, Option<T> newRecord);

  void remove(String recordKey);

  Map<String, Long> getCDCWriteStats();

  @Override
  void close();
}
