/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hudi.functional

import org.apache.hudi.DataSourceWriteOptions
import org.apache.hudi.config.HoodieWriteConfig

import org.apache.spark.sql.{DataFrame, SparkSession}

/**
 * The checked-in single-field ComplexKeyGenerator fixture tables under
 * `upgrade-downgrade-fixtures/complex-keygen-tables/`, written by the actual releases (see the README there):
 * MOR tables keyed on `id`, partitioned by `partition,category`, holding `id1` to `id8` after three commits.
 * The 0.14.0 table (version 6) stores `id:<value>` record keys; the 0.14.1 (version 6, `-bare` suffix), 1.0.2
 * (version 8) and 1.1.0 (version 9) tables store the bare value. None of them carries the encoding property.
 */
object ComplexKeyGenFixtures {

  val COMPLEX_KEYGEN_FIXTURES_PATH = "/upgrade-downgrade-fixtures/complex-keygen-tables/"
  val COMPLEX_KEYGEN_FIXTURE_SUFFIX = "-complex-keygen"
  val COMPLEX_KEYGEN_BARE_FIXTURE_SUFFIX = "-complex-keygen-bare"

  val FIXTURE_RECORD_KEY_FIELD = "id"
  val FIXTURE_PARTITION_FIELDS = "partition,category"
  val FIXTURE_IDS: Seq[String] = (1 to 8).map(i => s"id$i")

  /** The (partition, category) each fixture record lives in, as generated by the fixture script. */
  private val FIXTURE_PARTITIONS: Map[String, (String, String)] = Map(
    "id1" -> ("2023-01-01", "a"), "id2" -> ("2023-01-01", "b"),
    "id3" -> ("2023-01-02", "a"), "id4" -> ("2023-01-02", "b"),
    "id5" -> ("2023-01-03", "a"), "id6" -> ("2023-01-03", "a"),
    "id7" -> ("2023-01-04", "b"), "id8" -> ("2023-01-04", "b"))

  /** Write options matching the fixture's table config, the way the release that wrote it was configured. */
  def fixtureWriteOpts(tableName: String): Map[String, String] = Map(
    "hoodie.insert.shuffle.parallelism" -> "2",
    "hoodie.upsert.shuffle.parallelism" -> "2",
    "hoodie.delete.shuffle.parallelism" -> "2",
    DataSourceWriteOptions.PRECOMBINE_FIELD.key -> "ts",
    DataSourceWriteOptions.RECORDKEY_FIELD.key -> FIXTURE_RECORD_KEY_FIELD,
    DataSourceWriteOptions.PARTITIONPATH_FIELD.key -> FIXTURE_PARTITION_FIELDS,
    DataSourceWriteOptions.KEYGENERATOR_CLASS_NAME.key -> "org.apache.hudi.keygen.ComplexKeyGenerator",
    DataSourceWriteOptions.TABLE_TYPE.key -> DataSourceWriteOptions.MOR_TABLE_TYPE_OPT_VAL,
    HoodieWriteConfig.TBL_NAME.key -> s"${tableName}_table")

  /** Rows in the fixture schema for the given ids, in the partitions the fixture stores them, with the given ordering value. */
  def fixtureRows(spark: SparkSession, ids: Seq[String], ts: Long): DataFrame = {
    val rows = ids.map { id =>
      val (partition, category) = FIXTURE_PARTITIONS.getOrElse(id, ("2023-01-05", "a"))
      (id, s"${id}_$ts", ts, partition, category)
    }
    spark.createDataFrame(rows).toDF("id", "name", "ts", "partition", "category")
  }
}
