val hudiDf = spark.read.format("org.apache.hudi").load("/tmp/hudi-utilities-test/")
val inputDf = spark.read.format("json").load("/opt/bundle-validation/data/utilities/data")
hudiDf.registerTempTable("hudi_tbl")
inputDf.registerTempTable("src_tbl")
val hudiCount = spark.sql("select distinct date, key from hudi_tbl").count()
val srcCount = spark.sql("select distinct date, key from src_tbl").count()
if (hudiCount == srcCount) System.exit(0)
println(s"Counts don't match hudiCount: $hudiCount, srcCount: $srcCount")
System.exit(1)
