source 'https://gems.ruby-china.com'

# gem "github-pages", group: :jekyll_plugins

gem "tzinfo-data"
gem "wdm", "~> 0.1.0" if Gem.win_platform?

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jemoji"
  gem "jekyll-include-cache"
  gem "jekyll-algolia"
end
