/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.hudi.analysis

import org.apache.hudi.SparkAdapterSupport
import org.apache.hudi.client.common.HoodieSparkEngineContext
import org.apache.hudi.common.config.HoodieMetadataConfig
import org.apache.hudi.common.config.TypedProperties
import org.apache.hudi.common.index.vector.{ScoredVectorPostingMatch, VectorDistanceMetric, VectorIndexArbiter, VectorIndexMdtSearchUtils, VectorIndexMetadataCache, VectorIndexOptions, VectorPostingMatch, VectorStalePolicy}
import org.apache.hudi.common.model.{FileSlice, HoodieIndexDefinition, HoodieRecord}
import org.apache.hudi.common.schema.HoodieSchema
import org.apache.hudi.common.table.{HoodieTableMetaClient, TableSchemaResolver}
import org.apache.hudi.common.table.timeline.{HoodieTimeline, InstantComparison}
import org.apache.hudi.common.table.timeline.InstantComparison.compareTimestamps
import org.apache.hudi.common.table.view.HoodieTableFileSystemView
import org.apache.hudi.data.HoodieJavaRDD
import org.apache.hudi.hadoop.fs.HadoopFSUtils
import org.apache.hudi.metadata.{HoodieTableMetadata, HoodieTableMetadataUtil}

import org.apache.spark.api.java.JavaSparkContext
import org.apache.spark.rdd.RDD
import org.apache.spark.sql.{AnalysisException, DataFrame, Row, SparkSession}
import org.apache.spark.sql.catalyst.InternalRow
import org.apache.spark.sql.catalyst.parser.ParseException
import org.apache.spark.sql.catalyst.plans.logical.HoodieVectorSearchTableValuedFunction
import org.apache.spark.sql.catalyst.plans.logical.HoodieVectorSearchTableValuedFunction.{DistanceMetric, SearchAlgorithm}
import org.apache.spark.sql.catalyst.plans.logical.LogicalPlan
import org.apache.spark.sql.expressions.Window
import org.apache.spark.sql.functions.{broadcast, col, monotonically_increasing_id, row_number}
import org.apache.spark.sql.hudi.command.exception.HoodieAnalysisException
import org.apache.spark.sql.types.{ArrayType, ByteType, DataType, DoubleType, FloatType, Metadata, StructField, StructType}
import org.apache.spark.util.LongAccumulator
import org.slf4j.LoggerFactory

import scala.collection.JavaConverters._
import scala.collection.mutable.ArrayBuffer
import scala.util.{Failure, Success, Try}

case class VectorSearchTable(df: DataFrame, basePath: Option[String])

/**
 * Extension point for vector search algorithms. Each implementation provides
 * the Spark logical plan for single-query and batch-query KNN search.
 *
 * To add a new algorithm (e.g. RowMatrix, HNSW):
 *  1. Create an object extending this trait
 *  2. Add a value to [[SearchAlgorithm]]
 *  3. Register the mapping in [[HoodieVectorSearchPlanBuilder.resolveAlgorithm]]
 *
 * Implementations can use the shared validation helpers on
 * [[HoodieVectorSearchPlanBuilder]] (validateEmbeddingColumn, validateBatchDimensions, etc.)
 * and the raw distance functions on [[VectorDistanceUtils]].
 *
 * The output schema contract:
 *  - Single-query: all corpus columns (minus the embedding column) + `_hudi_distance: Double`
 *  - Batch-query: all corpus columns (minus the embedding column) + clashing query columns
 *    (prefixed with `_hudi_query_`) + `_hudi_distance: Double` + `_hudi_query_index: Long`
 *  - Results are ordered by `_hudi_distance` ascending (lower = more similar)
 *  - `_hudi_query_index` is an opaque grouping identifier (not a sequential index). Values may be
 *    large non-contiguous numbers because they are generated by `monotonically_increasing_id()`.
 */
trait VectorSearchAlgorithm {

  /** Human-readable name for error messages and logging. */
  def name: String

  /**
   * Build a plan that finds the k nearest corpus rows to a single query vector.
   *
   * @param spark          active SparkSession
   * @param corpusTable    resolved corpus table (may be Hudi, Parquet, or temp view)
   * @param embeddingCol   name of the array-typed embedding column in corpusDf
   * @param queryVector    the query vector, normalized to Array[Double]
   * @param k              number of nearest neighbors to return
   * @param metric         distance metric (COSINE, L2, DOT_PRODUCT)
   * @return an analyzed LogicalPlan whose output matches the single-query schema contract
   */
  def buildSingleQueryPlan(
      spark: SparkSession,
      corpusTable: VectorSearchTable,
      embeddingCol: String,
      queryVector: Array[Double],
      k: Int,
      metric: DistanceMetric.Value,
      runtimeOptions: Map[String, String] = Map.empty): LogicalPlan

  /**
   * Build a plan that finds the k nearest corpus rows for each row in the query table.
   *
   * @param spark              active SparkSession
   * @param corpusTable        resolved corpus table
   * @param corpusEmbeddingCol name of the embedding column in corpusDf
   * @param queryDf            resolved query DataFrame
   * @param queryEmbeddingCol  name of the embedding column in queryDf
   * @param k                  number of nearest neighbors per query
   * @param metric             distance metric (COSINE, L2, DOT_PRODUCT)
   * @return an analyzed LogicalPlan whose output matches the batch-query schema contract
   * @note Batch mode broadcasts the query table to all executors via a cross-join.
   *       This is designed for small-to-medium query sets (tens to low hundreds of rows).
   *       For large query tables, memory pressure on executors may occur.
   */
  def buildBatchQueryPlan(
      spark: SparkSession,
      corpusTable: VectorSearchTable,
      corpusEmbeddingCol: String,
      queryDf: DataFrame,
      queryEmbeddingCol: String,
      k: Int,
      metric: DistanceMetric.Value,
      runtimeOptions: Map[String, String] = Map.empty): LogicalPlan
}

/**
 * Resolves [[SearchAlgorithm]] values to [[VectorSearchAlgorithm]] implementations
 * and provides shared validation helpers used across algorithms.
 */
object HoodieVectorSearchPlanBuilder {

  private[analysis] val LOG = LoggerFactory.getLogger(getClass)

  val DISTANCE_COL = "_hudi_distance"
  val FILE_GROUP_ID_COL = "_hudi_file_group_id"
  val VECTOR_ONLY_PROJECTION_OPT = "vector.exact_fetch.vector_only_projection"
  val VECTOR_ONLY_PROJECTION_SPARK_CONF = "spark.hudi.vector.exact_fetch.vector_only_projection"
  private[analysis] val QUERY_ID_COL = "_hudi_query_index"
  private[analysis] val QUERY_EMB_ALIAS = "_hudi_query_emb"
  private[analysis] val RANK_COL = "_hudi_rank"
  private[analysis] val QUERY_COL_PREFIX = "_hudi_query_"

  private[analysis] def elapsedMs(startNs: Long): Long = (System.nanoTime() - startNs) / 1000000L

  private[analysis] def summarizeInts(values: Seq[Int], limit: Int = 16): String = {
    val preview = values.take(limit).mkString("[", ", ", "]")
    if (values.length > limit) s"$preview...(${values.length} total)" else preview
  }

  private[analysis] def summarizeShardCounts(shardCounts: collection.Map[Int, Int], limit: Int = 16): String = {
    val preview = shardCounts.toSeq.sortBy(_._1).take(limit).map { case (clusterId, count) =>
      s"$clusterId->$count"
    }.mkString("[", ", ", "]")
    if (shardCounts.size > limit) s"$preview...(${shardCounts.size} total)" else preview
  }

  private[analysis] def logRddLineage(label: String, rdd: RDD[_]): Unit = {
    Try(rdd.toDebugString) match {
      case Success(debug) =>
        LOG.info(s"[vector_search][$label] lineage:\n$debug")
      case Failure(error) =>
        LOG.warn(s"[vector_search][$label] unable to fetch RDD lineage", error)
    }
  }

  /** Resolve a [[SearchAlgorithm]] enum value to its implementation. */
  def resolveAlgorithm(algorithm: SearchAlgorithm.Value): VectorSearchAlgorithm = algorithm match {
    case SearchAlgorithm.BRUTE_FORCE => BruteForceSearchAlgorithm
    case SearchAlgorithm.IVF_RABITQ_MDT => IvfRaBitQMdtSearchAlgorithm
    case other => throw new HoodieAnalysisException(
      s"Unsupported search algorithm: $other")
  }

  private[analysis] def validateEmbeddingColumn(df: DataFrame, colName: String): Unit = {
    val fieldOpt = df.schema.fields.find(_.name.equalsIgnoreCase(colName))
    val field = fieldOpt.getOrElse(
      throw new HoodieAnalysisException(
        s"Embedding column '$colName' not found in table schema. " +
          s"Available columns: ${df.schema.fieldNames.mkString(", ")}"))
    field.dataType match {
      case ArrayType(FloatType, _) | ArrayType(DoubleType, _) | ArrayType(ByteType, _) => // valid
      case other =>
        throw new HoodieAnalysisException(
          s"Embedding column '$colName' has type $other, " +
            "expected array<float>, array<double>, or array<byte>")
    }
  }

  /**
   * Validates that the query vector dimension matches the corpus embedding dimension
   * when the corpus column has VECTOR(dim) metadata.
   */
  private[analysis] def validateQueryVectorDimension(
      df: DataFrame, embeddingCol: String, queryDim: Int): Unit = {
    extractVectorSchema(df, embeddingCol).map(_.getDimension).foreach { corpusDim =>
      if (corpusDim != queryDim) {
        throw new HoodieAnalysisException(
          s"Query vector dimension ($queryDim) does not match " +
            s"corpus embedding dimension ($corpusDim) for column '$embeddingCol'")
      }
    }
  }

  /**
   * Validates that corpus and query embedding columns have the same element type.
   *
   * This is a deliberate design choice: we require strict type matching rather than
   * silently upcasting (e.g. float to double). While some vector search systems
   * auto-convert, strict matching avoids subtle precision differences and makes
   * type mismatches between pipelines explicit. This can be relaxed to support
   * automatic widening (byte -> float -> double) in a future iteration if needed.
   */
  private[analysis] def validateElementTypeCompatibility(
      corpusDf: DataFrame, corpusCol: String,
      queryDf: DataFrame, queryCol: String): Unit = {
    val corpusElemType = getElementType(corpusDf, corpusCol)
    val queryElemType = getElementType(queryDf, queryCol)
    if (corpusElemType != queryElemType) {
      throw new HoodieAnalysisException(
        s"Corpus embedding column '$corpusCol' has element type $corpusElemType " +
          s"but query embedding column '$queryCol' has element type $queryElemType. " +
          "Both must use the same element type (e.g. array<float>).")
    }
  }

  /**
   * Validates that corpus and query embedding dimensions match when both have
   * VECTOR(dim) metadata.
   */
  private[analysis] def validateBatchDimensions(
      corpusDf: DataFrame, corpusCol: String,
      queryDf: DataFrame, queryCol: String): Unit = {
    (extractVectorSchema(corpusDf, corpusCol).map(_.getDimension), extractVectorSchema(queryDf, queryCol).map(_.getDimension)) match {
      case (Some(corpusDim), Some(queryDim)) if corpusDim != queryDim =>
        throw new HoodieAnalysisException(
          s"Corpus embedding dimension ($corpusDim) does not match " +
            s"query embedding dimension ($queryDim)")
      case _ => // dimensions match or metadata not available
    }
  }

  private[analysis] def getElementType(df: DataFrame, colName: String): DataType = {
    val field = df.schema.fields.find(_.name.equalsIgnoreCase(colName)).getOrElse(
      throw new HoodieAnalysisException(
        s"Embedding column '$colName' not found in table schema. " +
          s"Available columns: ${df.schema.fieldNames.mkString(", ")}"))
    field.dataType match {
      case ArrayType(elemType, _) => elemType
      case other =>
        throw new HoodieAnalysisException(
          s"Embedding column '$colName' has type $other, expected an array type")
    }
  }

  /** Extracts VECTOR schema from column metadata, if present. */
  private[analysis] def extractVectorSchema(df: DataFrame, colName: String): Option[HoodieSchema.Vector] = {
    df.schema.fields.find(_.name.equalsIgnoreCase(colName)).flatMap { field =>
      val meta = field.metadata
      if (meta.contains(HoodieSchema.TYPE_METADATA_FIELD)) {
        val typeDesc = meta.getString(HoodieSchema.TYPE_METADATA_FIELD)
        Try(HoodieSchema.parseTypeDescriptor(typeDesc)) match {
          case Success(v: HoodieSchema.Vector) => Some(v)
          case Success(_) => throw new HoodieAnalysisException(
            s"Column '$colName' has type '$typeDesc' which is not a VECTOR type. " +
              "Only VECTOR columns are supported for vector search.")
          case Failure(e) => throw new HoodieAnalysisException(
            s"Column '$colName' has malformed type metadata '$typeDesc': ${e.getMessage}")
        }
      } else None
    }
  }

  private[analysis] def quoteIdentifier(name: String): String = s"`${name.replace("`", "``")}`"
}

/**
 * Brute-force KNN vector search: computes distance between every corpus row and
 * every query vector, then selects the top-K closest.
 *
 * <p>Complexity: O(|corpus| * |queries| * dimensions) — linear scan with no index.
 *
 * <p><b>Single-query mode:</b> applies a distance UDF per corpus row, then
 * {@code orderBy + limit(k)} (Spark optimizes this to a partial sort via TakeOrderedAndProject).
 *
 * <p><b>Batch-query mode:</b> broadcast cross-joins the (small) query table with
 * the corpus, computes pairwise distances, then uses a window function to rank
 * and select top-K per query. The cross-join produces O(|corpus| * |queries|)
 * intermediate rows, so this is suitable for small-to-medium query sets
 * (tens to low hundreds of queries) against moderate corpora.
 */
object BruteForceSearchAlgorithm extends VectorSearchAlgorithm {

  import HoodieVectorSearchPlanBuilder._

  override val name: String = "brute_force"

  private def applyFilter(df: DataFrame, filterExpr: String): DataFrame = {
    try {
      df.filter(filterExpr)
    } catch {
      case e @ (_: ParseException | _: AnalysisException) =>
        throw new HoodieAnalysisException(
          s"Invalid pre-filter expression '$filterExpr': ${e.getMessage}")
    }
  }

  private def filterOption(runtimeOptions: Map[String, String]): Option[String] =
    runtimeOptions.get(HoodieVectorSearchTableValuedFunction.BRUTE_FORCE_FILTER_OPT)

  private def maxDistanceOption(runtimeOptions: Map[String, String]): Option[Double] =
    runtimeOptions.get(HoodieVectorSearchTableValuedFunction.BRUTE_FORCE_MAX_DISTANCE_OPT).map(_.toDouble)

  override def buildSingleQueryPlan(
      spark: SparkSession,
      corpusTable: VectorSearchTable,
      embeddingCol: String,
      queryVector: Array[Double],
      k: Int,
      metric: DistanceMetric.Value,
      runtimeOptions: Map[String, String] = Map.empty): LogicalPlan = {
    val corpusDf = corpusTable.df
    validateEmbeddingColumn(corpusDf, embeddingCol)
    validateQueryVectorDimension(corpusDf, embeddingCol, queryVector.length)

    val elemType = getElementType(corpusDf, embeddingCol)
    var filteredDf = corpusDf.filter(col(embeddingCol).isNotNull)
    filterOption(runtimeOptions).foreach(filter => filteredDf = applyFilter(filteredDf, filter))

    // Validate byte corpus query vector values before creating the UDF.
    if (elemType == ByteType) {
      queryVector.foreach { v =>
        if (v < Byte.MinValue || v > Byte.MaxValue)
          throw new HoodieAnalysisException(
            s"Query vector value $v is out of range for byte corpus [${Byte.MinValue}, ${Byte.MaxValue}]")
        if (v != v.toByte.toDouble)
          throw new HoodieAnalysisException(
            s"Query vector value $v is not a whole number. " +
              "Byte corpus embeddings require integer-valued query vectors.")
      }
    }

    // The single-query UDF closes over the pre-computed query DenseVector,
    // so only the corpus column is passed per row.
    val distanceUdf = VectorDistanceUtils.createSingleQueryDistanceUdf(metric, elemType, queryVector)

    var scored = filteredDf
      .withColumn(DISTANCE_COL, distanceUdf(col(embeddingCol)))
      .drop(embeddingCol)
    maxDistanceOption(runtimeOptions).foreach(distance =>
      scored = scored.filter(col(DISTANCE_COL) <= distance))
    val result = scored
      .orderBy(col(DISTANCE_COL).asc)
      .limit(k)

    result.queryExecution.analyzed
  }

  override def buildBatchQueryPlan(
      spark: SparkSession,
      corpusTable: VectorSearchTable,
      corpusEmbeddingCol: String,
      queryDf: DataFrame,
      queryEmbeddingCol: String,
      k: Int,
      metric: DistanceMetric.Value,
      runtimeOptions: Map[String, String] = Map.empty): LogicalPlan = {
    val corpusDf = corpusTable.df
    validateEmbeddingColumn(corpusDf, corpusEmbeddingCol)
    validateEmbeddingColumn(queryDf, queryEmbeddingCol)
    validateElementTypeCompatibility(corpusDf, corpusEmbeddingCol, queryDf, queryEmbeddingCol)
    validateBatchDimensions(corpusDf, corpusEmbeddingCol, queryDf, queryEmbeddingCol)

    val corpusElemType = getElementType(corpusDf, corpusEmbeddingCol)
    val distanceUdf = VectorDistanceUtils.createDistanceUdf(metric, corpusElemType)
    var filteredCorpus = corpusDf.filter(col(corpusEmbeddingCol).isNotNull)
    filterOption(runtimeOptions).foreach(filter => filteredCorpus = applyFilter(filteredCorpus, filter))

    // Prefix clashing query columns with "_hudi_query_" to avoid cross-join ambiguity when
    // corpus and query share column names (e.g. both have "id" or "embedding").
    val corpusCols = filteredCorpus.columns.toSet
    val queryWithId = queryDf.filter(col(queryEmbeddingCol).isNotNull)
      .withColumnRenamed(queryEmbeddingCol, QUERY_EMB_ALIAS)
      .withColumn(QUERY_ID_COL, monotonically_increasing_id())

    val renamedQuery = queryWithId.select(queryWithId.columns.map { qCol =>
      if (qCol != QUERY_ID_COL && qCol != QUERY_EMB_ALIAS && corpusCols.contains(qCol))
        col(qCol).as(s"$QUERY_COL_PREFIX$qCol")
      else
        col(qCol)
    }: _*)

    // Cross join corpus with broadcast queries, compute distance, then rank
    var scored = filteredCorpus.crossJoin(broadcast(renamedQuery))
      .withColumn(DISTANCE_COL,
        distanceUdf(col(corpusEmbeddingCol), col(QUERY_EMB_ALIAS)))
      .drop(corpusEmbeddingCol)
      .drop(QUERY_EMB_ALIAS)
    maxDistanceOption(runtimeOptions).foreach(distance =>
      scored = scored.filter(col(DISTANCE_COL) <= distance))

    val window = Window.partitionBy(QUERY_ID_COL).orderBy(col(DISTANCE_COL).asc)
    val result = scored
      .withColumn(RANK_COL, row_number().over(window))
      .filter(col(RANK_COL) <= k)
      .drop(RANK_COL)
      .orderBy(col(QUERY_ID_COL), col(DISTANCE_COL))

    result.queryExecution.analyzed
  }

}
