################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: basic-example
spec:
  image: localhost:5001/hudi/hudi-flink:latest
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
    execution.checkpointing.checkpoints-after-tasks-finish.enabled: "true"
    state.backend.type: filesystem
    state.savepoints.dir: s3a://test/savepoints/
    state.checkpoints.dir: s3a://test/checkpoints/
    s3.access-key: minioadmin
    s3.secret-key: minioadmin
    s3.endpoint: http://minio-svc:9000
    s3.path.style.access: "true"
    s3a.access-key: minioadmin
    s3a.secret-key: minioadmin
    s3a.endpoint: http://minio-svc:9000
    s3a.path.style.access: "true"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "1g"
      cpu: 1
    podTemplate:
      spec:
        containers:
          - name: flink-main-container
            env:
              - name: TARGET_S3_PATH
                value: 's3a://test/hudi'
  taskManager:
    resource:
      memory: "1g"
      cpu: 1
  job:
    jarURI: local:///opt/hudi/examples/streaming/hudi-examples-k8s.jar
    parallelism: 2
    upgradeMode: stateless