/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const { originalSlackUrl } = require('./constants');

module.exports = {
  community: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'link',
      label: 'Github',
      href: 'https://github.com/apache/hudi',
    },
    {
      type: 'link',
      label: 'Slack',
      href: originalSlackUrl,
    },
    {
      type: 'link',
      label: 'LinkedIn',
      href: 'https://www.linkedin.com/company/apache-hudi/',
    },
    {
      type: 'link',
      label: 'YouTube',
      href: 'https://www.youtube.com/@apachehudi',
    },
    {
      type: 'link',
      label: 'X',
      href: 'https://x.com/ApacheHudi',
    },
  ],
};
