# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# to be used with test-aggressive-clean-archival.properties

dag_name: deltastreamer-long-running-multi-partitions.yaml
dag_rounds: 20
dag_intermittent_delay_mins: 1
dag_content:
  first_insert:
    config:
      record_size: 1000
      num_partitions_insert: 50
      repeat_count: 1
      num_records_insert: 1000
    type: InsertNode
    deps: none
  second_insert:
    config:
      record_size: 1000
      num_partitions_insert: 50
      repeat_count: 1
      num_records_insert: 10000
    deps: first_insert
    type: InsertNode
  third_insert:
    config:
      record_size: 1000
      num_partitions_insert: 50
      repeat_count: 1
      num_records_insert: 300
    deps: second_insert
    type: InsertNode
  first_upsert:
    config:
      record_size: 1000
      num_partitions_insert: 50
      num_records_insert: 300
      repeat_count: 1
      num_records_upsert: 100
      num_partitions_upsert: 50
    type: UpsertNode
    deps: third_insert
  first_delete:
    config:
      num_partitions_delete: 50
      num_records_delete: 8000
    type: DeleteNode
    deps: first_upsert
  second_validate:
    config:
      validate_once_every_itr : 5
      validate_hive: false
      delete_input_data: false
      max_wait_time_for_deltastreamer_catch_up_ms: 600000
    type: ValidateDatasetNode
    deps: first_delete
  last_validate:
    config:
      execute_itr_count: 20
      max_wait_time_for_deltastreamer_catch_up_ms: 600000
    type: ValidateAsyncOperations
    deps: second_validate
