name: Add GH PR to Support Project

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  add-to-project:
    name: Add PR to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/apache/projects/150
          github-token: ${{ secrets.GITHUB_TOKEN }}
