name: Label PR

on: [ pull_request ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  issues: write
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size-xs'
          xs_max_size: '10'
          s_label: 'size-s'
          s_max_size: '100'
          m_label: 'size-m'
          m_max_size: '500'
          l_label: 'size-l'
          l_max_size: '1000'
          xl_label: 'size-xl'
          fail_if_xl: 'false'
          github_api_url: 'api.github.com'
          files_to_ignore: ''