name: Update Pr Compliance

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - master
    paths:
      - scripts/pr_compliance.py
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: run script
        run: python3 scripts/pr_compliance.py run-tests > test.log || { echo "::error::pr_compliance.py $(cat test.log)" && exit 1; }
